const SupplierCategoryConfig = {
  MarketplaceID: 'SEB',
  MarketplaceName: 'Self Esteem Brands',
  ServiceCategories: [
    'Accounting Services and Software',
    'AEDs & Accessories',
    'Air Fragrance Systems',
    'Apparel AF Staff Uniforms',
    'Apparel and Promotional Products',
    'Billing',
    'Body Composition Solutions',
    'Cleaning Services',
    'Cleaning Supplies  & Equipment Wipes',
    'Club Design & Construction',
    'Club Management Software',
    'Club Rental Services',
    'Collection Agency',
    'Employment & Labor Law Toolkit and Resources',
    'Employment Services',
    'Facility Equipment',
    'Fans',
    'Financing/Lender',
    'First Aid & Safety',
    'Fitness Accessories',
    'Fitness Education',
    'Fitness Equipment',
    'Fitness Incentives Programs/Processor',
    'Free Weights',
    'Heart Zoning Solutions',
    'Insurance - Club',
    'Insurance ? Health Club Surety Bonds',
    'Lease Management & Audit',
    'Market Expansion Line/Call Answering Service',
    'Marketing - Digital/Social Media',
    'Marketing - Direct Mail',
    'Marketing - Email & CRM',
    'Marketing - Print Packages, Promotion Signage, Outdoor Events',
    'Merchant & Credit Card Services',
    'Music',
    'Mystery Shopping Services',
    'Non-Profit Fitness Association',
    'Office Supplies',
    'PT Sales Consulting',
    'Real Estate',
    'Resale Products',
    'Security & Hardware Installation',
    'Signage - Exterior',
    'Signage - Interior',
    'Supplements & Nutrition',
    'Tanning',
    'TV and Connection Solutions',
    'Vending Machines',
    'Insurance ? Club',
    'Resale',
    'Signage ? Interior',
    'Accounting Services',
    'Apparel & Promotional Products',
    'Business Texting Software',
    'Equipment',
    'Financial Management Software & Processing',
    'Financing',
    'First Aid Kits',
    'Floor Mat Service',
    'General Office Supplies',
    'Hand Dryers',
    'Hiring Management Software',
    'Insurance - Studio',
    'Linens',
    'Marketing  - Digital/Social Media',
    'Marketing - Email',
    'Marketing - Print Packages, Promotion signage, Outdoor Events',
    'On-Hold Messaging Service',
    'Pre-Employment Screening Services',
    'Security & Technology',
    'Signing',
    'Studio Design & Construction',
    'Studio Management Software',
    'Studio Rental Services',
    'Studio Surety Bonds',
    'Supplies: Color, Tools',
    'Uniforms',
    'Wax',
    'Wipes and Cleaning Supplies',
  ],
  VendorLevels: ['PREFERRED', 'DESIGNATED', 'MANDATED', 'EXCLUSIVE DESIGNATED'],
};

export default SupplierCategoryConfig;
